build/npm/lib/FocusTrap.js
build/npm/lib/HotKeyMapMixin.js
build/npm/lib/HotKeys.js
build/npm/lib/index.js
lib/HotKeys.js

Without this in current 0.0.3 I get (obviously) `document is not defined` when doing server render.
The only change is at the very bottom (commited `build/npm/lib` so that I can use this myself, feel free to to tell me remove all `build/npm/*` changes for the pull request to happen).

Support React's server rendering.

---

lib/HotKeys.js

reset __lastChildSequence__ on parent hotkey when a child hotkey loses focus

---

lib/HotKeys.js

this.updateMap is not called when handlers are changed due to
short-circuiting

fix key map update

---

index.d.ts

This change should allow users to set props like 'className' on HotKeys components without TypeScript generating errors.
I'm not 100% sure about these changes, but I've tested this locally and it seems to be working fine.

Update TypeScript interface for HotKeys

---

index.d.ts

I was trying to attach the hotkeys to the `window`, as suggested here: https://github.com/greena13/react-hotkeys/issues/12#issuecomment-128278693. Unfortunately, that does not work at the moment when compiling using Typescript, as the `attach` property only accepts elements or components.
```
[...]
Types of property 'attach' are incompatible.
Type 'Window' is not assignable to type 'Element | Component<{}, {}> | undefined'.
```
Luckily it's a simple fix, by adding `Window` as an accepted type for the `attach` property.

Fix attaching hotkeys to the window in TS definition file

---

lib/FocusTrap.js

If you try to pass a custom component you get the following warning
`Failed prop type: Invalid prop 'component' supplied to 'FocusTrap'.`
[Sandbox](https://codesandbox.io/s/qz7j6537vq)

fix proptype declaration

---

lib/withHotKeys.js

Refactored withHotKeys.js to avoid calling `.bind(this)` every time when a hot key is pressed.

Refactored withHotKeys.js to avoid calling `.bind(this)` all the time.

---

lib/HotKeys.js

Hey,
we encountered the following problem:
1a) We had a parent HotKeys component that handled `enter`.
1b) We had a child HotKeys component that handled `enter` aswell.
2) After the childs handler was called (after pressing enter) we removed the child's handler for `enter`.
3) The parents handler was still blocked by `__lastChildSequence__ ` although the child doesn't have a handler for that anymore
With the proposed change, this case works for us.
Best
Ansgar

Fixed bug blocking parent handler after removing sequence from child

---

lib/withHotKeys.js

Adds support for the `focused` and `attach` props for the `withHotKeys()` HOC, as per the discussion in #96.

Add support for additional props to HOC

---

package.json
yarn.lock

When I tried to `npm install` a fresh clone on windows I got errors from the environment variables set by the build commands.
Add an npm module `cross-env` that allows for commands that set environment variables to function cross platform.

Cross-platform build commands

---

lib/FocusTrap.js
lib/HotKeys.js

This allows access to the underlying DOM wrapper node, which is useful if you need to call `focus`. In my use case I have several different `HotKeys` components on different parts of the page, and want to pass focus from one to another. They don't always have children with a tabindex, so there is no other element to add a ref to. Another option could be using `state` and the `focused` property, but in my testing the `focused` property doesn't really seem to work.
The `innerRef` pattern seems to be idiomatic, being used by e.g. [react-router](https://github.com/ReactTraining/react-router) and [formik](https://github.com/jaredpalmer/formik).
Another option would be using [ref forwarding](https://reactjs.org/docs/forwarding-refs.html), but that would be backwards-incompatible for anyone …

Provide an innerRef prop

---

index.d.ts

refer to: <https://github.com/Microsoft/TypeScript/issues/5683#issuecomment-260430159>
I'm pretty sure this version of declaration is perfect. I've passed tsc.

Fix index key declaration

---

README.md

* Migrates from `React.createClass` to functional components in documentation
* Applies `prettier` to the markdown file, resulting in some super pretty tables ✨

apply prettier to readme and migrate examples to functional components

---

index.d.ts

`HTMLInputElement` only supports for input elements, but even in `Readme` there is ref for divs. With current typing, it's not possible. With this addition its possible to set ref to any `HTML` element.

Improve types for innerRef

---

src/HotKeys.js

Fixed the prop type for innerRef to receive function as value for cases where ref is not instantiated using `React.createRef`.
Current behavior:

Fixed innerRef prop type in HotKeys

---

index.d.ts

This fixes types for me, not positive it's what you want exactly but seems to translate correctly.

Type ref properly

---

index.d.ts

```
ignoreEventsCondition?: (KeyboardEvent) => boolean,
```
should be
```
ignoreEventsCondition?: (keyEvent: KeyboardEvent) => boolean,
```

fixed a type definition error

---

src/const/KeysWithoutPressEventDictionary.js
src/const/SpecialKeysDictionary.js
src/helpers/parsing-key-maps/isValidKey.js
test/HotKeys/focus-only/ActionAndHandlerResolution.spec.js
test/IgnoreKeys/IgnoringKeyEvents.spec.js

The `Backspace` key was not being correctly resolved, causing it to raise an error when [used with the IgnoreKeys component](https://github.com/greena13/react-hotkeys/issues/172).
* (Hopefully) fixed the resolution of `Backspace` key events for good.
* Gives that (custom) error a `name` attribute, so it's more evident what the underlying problem was.

🐛 Fix #172: Fix resolving the Backspace key

---

src/lib/strategies/AbstractKeyEventStrategy.js
src/lib/strategies/FocusOnlyKeyEventStrategy.js
src/lib/strategies/GlobalKeyEventStrategy.js
test/HotKeys/BindingToKeysWithSimulatedKeypressEvents.spec.js
test/support/FocusableElement.js

There is a subroutine that is run on the `keyup` event that checks the current `KeyBoardEvent`'s modifier key flags (e.g. `metaKey`) and compares it against the key state that `react-hotkeys` is maintaining. It then corrects for any discrepancies (missed key events, most likely due to a focus loss) in the `react-hotkeys` record of key state. 
On the `keyup` event for a modifier key (e.g. Command/`Meta`), its own corresponding modifier key flag  (e.g. `metaKey`) is false. This was causing registering the key as being in the `keyup` state twice, resulting in #166 whereby handlers bound to the `keyup` event of the `Meta` key were not being called.
* Adds additional logic to detect the exceptional case when it's a modifier key that is in the `keyup` state, and skips running the subroutine
* …

Fix #166: Fix over-zealous modifier flag discrepancy correction

---

README.md
index.d.ts
src/helpers/resolving-handlers/isMatchPossibleBasedOnNumberOfKeys.js
src/lib/Configuration.js
src/lib/strategies/AbstractKeyEventStrategy.js
test/GlobalHotKeys/MatchingHotKeyCombinationsWhenAllowCombinationSubmatchesIsFalse.spec.js
test/GlobalHotKeys/MatchingHotKeyCombinationsWhenAllowCombinationSubmatchesIsTrue.spec.js
test/HotKeys/MatchingSingleHotKeysWhenAllowCombinationSubmatchesIsFalse.spec.js
test/HotKeys/MatchingSingleHotKeysWhenAllowCombinationSubmatchesIsTrue.spec.js
test/HotKeys/focus-only/ChangingKeyMapAndHandlersAfterMount.spec.js
test/HotKeys/focus-only/HandlersThatChangeFocus.spec.js
test/HotKeys/focus-only/MatchingHotKeyCombinations.spec.js

The current action matching behaviour of `react-hotkeys` has caused confusion and seemed to contradict user's expectations a couple of times  (#161, #181, #175): It first examines `<HotKeys/>` components closest to the element currently in focus, and then moves towards the top of the app, examining the full hierarchy of focused `<HotKeys />` components, before moving on to `<GlobalHotkeys/>`. 
The trouble is that submatches are allowed in this matching process: If an application has a context-dependent action, bound to a short key combination (e.g. `?`) and a longer global action bound to a longer key combination (e.g. `shift+?`) the longer key combination is hidden behind the shorter one and never triggered whenever a child of the `<HotKeys/>` component that defines the shorter …

Dev ignore submatches

---

README.md
src/helpers/parsing-key-maps/keyIsCurrentlyTriggeringEvent.js
src/lib/KeyEventManager.js
src/lib/strategies/AbstractKeyEventStrategy.js
src/lib/strategies/FocusOnlyKeyEventStrategy.js
src/lib/strategies/GlobalKeyEventStrategy.js
test/GlobalHotKeys/ClosingHangingCombinationsInHotKeysComponents.spec.js
test/GlobalHotKeys/ClosingKeyCombinationsStartedInHotKeys.spec.js

A recent pull request (#186) switched from observing key combination submatches, to ignoring them by default. This revealed there is an issue (#187) with key events being missed by React HotKeys in circumstances where an action is defined with a handler that changes the React DOM or focused element in such a way that the new focused element is outside of any <HotKeys /> descendants, resulting in the corresponding keyup event never being logged - and react-hotkeys behaving as if the key is still held down.
One possible (partial) solution to this problem was the addition of a `root` prop for `HotKeys` components (#187). This has its advantages of not requiring binding to the document, and remaining relatively self-contained. However, it's limited in its scope and not all users can or want …

Dev closing hanging combinations

---

README.md
examples/src/App.js
index.d.ts
src/lib/strategies/AbstractKeyEventStrategy.js
src/utils/object/copyAttributes.js
src/withHotKeys.js
test/HotKeys/SpecifyingKeyMapUsingObjects.spec.js
test/getApplicationKeyMap/GettingApplicationKeyMap.js

The current ability to display an application's keymap was implemented as somewhat of a litmus test to see how useful users of `react-hotkeys` would find it. It didn't take long for the capacity of the feature to be exceeded, and more functionality to be requested (#154).
* Adds the ability for users to specify `name`, `description` and `group` attributes for each key map that they define.
This can be done using the existing object syntax:
```javascript
{
'ACTION1': {
sequence: 'enter',
name: 'NAME',
description: 'DESC',
group: 'GROUP'
}
}
```
Or using an new syntax, for when the user also has multiple alternative key sequences to trigger the same action:
```javascript
{
'ACTION1': {
sequences: ['enter', 'shift'],
name: 'NAME',
description: 'DESC',
group: 'GROUP'
}
}
```
* Necessarily …

🌟 #154: Add ability to specify name, group and description to keys

---

src/lib/strategies/FocusOnlyKeyEventStrategy.js
test/HotKeys/focus-only/ChangingKeyMapAndHandlersAfterMount.spec.js

Back in #150 the handler state not being reset when a new `<GlobalHotKeys />` is mounted was fixed, but the analogous situation for `<HotKeys />` was left unfixed (when a `<HotKeys />` component updates its props). This resulted in the issue #182, whereby if a `<HotKeys />` component's props had changed (and the `allowChanges` prop was used) and a key had already been pressed (triggering the building of a handler resolution data structure), then the key handler was *not* updated, and the old one was used.
* Resets the `<HotKeys />` component's handler resolution state whenever it updates its props (and `allowChanges` is true).
* Adds a test to cover this situation in the future

🐛 Fix #182: Reset handle resolution state when HotKeys props are updated

---

README.md
index.d.ts
src/lib/Configuration.js
src/lib/strategies/FocusOnlyKeyEventStrategy.js
src/lib/strategies/GlobalKeyEventStrategy.js
test/lib/IgnoringRepeatedEvents.spec.js

When an end-user holds down certain modifier keys and a non-modifier key at the same time (e.g. `shift+a`) the browser repeatedly registers `keydown` and `keypress` events for the non-modifier key. This results in any action bound to that key combination being repeatedly called, which is unlikely what the developer intends. This has been reported as a bug in #177.
* Adds  a `ignoreRepeatedEventsWhenKeyHeldDown` configuration option that is `true` by default, and causes all repeated `keydown` and `keypress` events to be ignored by `react-hotkeys`.
* Adds a test that covers this new functionality
* Adds the corresponding TypeScript and Readme entries for the new `ignoreRepeatedEventsWhenKeyHeldDown` option

🐛 Fix #177: Ignore repeated keyboard events when a key is held down

---

index.d.ts

Currently TS will complain that `only` and `except` props are required when using `ObserveKeys` or `IgnoredKeys`

Fix HotkeysOverrideProps to be optional

---

src/helpers/resolving-handlers/isMatchPossibleBasedOnNumberOfKeys.js
src/lib/Configuration.js
src/lib/strategies/AbstractKeyEventStrategy.js
test/GlobalHotKeys/HoldingDownKeySharedByActions.spec.js

When the `Cmd` (`Meta`) key is pressed down with other keys, it hides their `keyup` events, and only the `Meta` key `keyup` event is triggered. `react-hotkeys` accounts for this and simulates the `keyup` events for all the keys `Meta` was pressed down with, when the its `keyup` event is detected.
However, if you hold down `Meta` with another key, release the other key and press a third key while `Meta` is still down, `react-hotkeys` does not know the first key has been released until you also release `Meta`. So for example, if you press `Meta` down, then `a`, then release `a` and press `b` - `react-hotkeys` thinks you're still holding `Meta+a+b` until you release `Meta`. This is undesirable, but (so far as I can come up with) unavoidable, and generally does not cause problems. 
When it …

🐛 Fix #201: Always allow submatches for combinations involving command

---

src/lib/KeyEventManager.js

Using `window.onblur` might overwrite the user's `onblur` who is using this library.
Fixes #236

🐛 Use addEventListener instead of window.onblur

---

test/support/FocusableElement.js

`getInstance` isn't currently used, but clearly this will need fixing if it is going to be!

🐛 fix typo in FocusableElement
